version: "3.8"
   
services:
    django:
        restart: always
        build: .
        container_name: django
        command: bash -c "./wait-for-db.sh && python manage.py runserver 0.0.0.0:8000"
        volumes:
            - .:/usr/src/app
        ports:
            - "8000:8000"
        depends_on:
            - pgdb
    pgdb:
        image: postgres
        container_name: pgdb
        ports:
            - "5432:5432"
        environment:
        - POSTGRES_DB=postgres
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgres
